# Generated by Django 3.2.4 on 2022-04-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_api', '0002_alter_roomavailability_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='is_married',
            field=models.BooleanField(default=False),
        ),
    ]
