# Generated by Django 3.2.4 on 2022-05-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_api', '0004_auto_20220501_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomavailability',
            old_name='day_date',
            new_name='day_date_from',
        ),
        migrations.AddField(
            model_name='roomavailability',
            name='day_date_till',
            field=models.DateTimeField(null=True),
        ),
    ]
