# Generated by Django 3.2.4 on 2022-04-19 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bill_of_material', '0005_bill_of_material_is_in_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comboName', models.CharField(max_length=15)),
                ('comboPrice', models.FloatField()),
                ('comboPriceAfterDiscount', models.FloatField()),
                ('comboItems', models.ManyToManyField(to='bill_of_material.Bill_of_material')),
                ('userLinked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField()),
                ('orderDate', models.DateField(auto_now=True)),
                ('orderPrice', models.FloatField()),
                ('userLinked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderComboItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('totolAmount', models.FloatField()),
                ('comboAssociated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_order_and_menu_system.combo')),
                ('orderAssociated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_order_and_menu_system.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBomItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('totolAmount', models.FloatField()),
                ('bomAssociated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_of_material.bill_of_material')),
                ('orderAssociated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_order_and_menu_system.order')),
            ],
        ),
    ]
