# Generated by Django 3.2.4 on 2022-02-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0005_product_product_weight_per_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='totalquanitity',
            field=models.IntegerField(default=0),
        ),
    ]
