# Generated by Django 3.2.4 on 2022-02-18 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bill_of_material', '0002_bill_of_material_kitchen_inventory_item_kitchenitemassociated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_of_material',
            name='userLinked',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
