# Generated by Django 3.2.4 on 2022-02-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_material', '0003_bill_of_material_userlinked'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_of_material',
            name='photo',
            field=models.ImageField(default=0, upload_to='billOfMaterial'),
            preserve_default=False,
        ),
    ]
