# Generated by Django 3.2.4 on 2022-04-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_material', '0004_bill_of_material_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_of_material',
            name='is_in_menu',
            field=models.BooleanField(default=False),
        ),
    ]
