# Generated by Django 3.2.4 on 2022-04-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_material', '0005_bill_of_material_is_in_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_of_material',
            name='is_drink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill_of_material',
            name='is_nonVeg',
            field=models.BooleanField(default=False),
        ),
    ]
